apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::793948481411:role/eksctl-favorite-movies-cluster-nod-NodeInstanceRole-xGdtq0EUliZM
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::793948481411:user/balajisachidanandam
      username: balajisachidanandam
      groups:
        - system:masters
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::793948481411:role/eksctl-favorite-movies-cluster-nod-NodeInstanceRole-xGdtq0EUliZM\n  username: system:node:{{EC2PrivateDNSName}}\n","mapUsers":"- userarn: arn:aws:iam::793948481411:user/balajisachidanandam\n  username: balajisachidanandam\n  groups:\n    - system:masters\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2024-12-24T15:06:26Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"1452","uid":"30ae69cb-6c93-4d9e-a8fb-67562699e93e"}}
  creationTimestamp: "2024-12-24T15:06:26Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "128780"
  uid: 30ae69cb-6c93-4d9e-a8fb-67562699e93e
