apiVersion: v1
kind: Service
metadata:
  name: favorite-movies-frontend-service
spec:
  selector:
    app: favorite-movies-frontend
  ports:
    - protocol: TCP
      port: 80 # Port exposed by the service
      targetPort: 3000 # Port your application listens on (Next.js default)
  type: LoadBalancer # Creates an AWS load balancer to expose externally
